### ISSUE TITLE
[Quest] Lab Work

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#249]
http://www.wow-mania.com/armory/?quest=12557

http://www.wow-mania.com/armory/?npc=28205 gives this quest. The quest requires you to collect four items http://www.wow-mania.com/armory/?item=38386 http://www.wow-mania.com/armory/?item=38339  http://www.wow-mania.com/armory/?item=38340  http://www.wow-mania.com/armory/?item=38346 

He is supposed to announce what items you need out loud but doesn't. If you go into the side rooms to collect the items they are not recognised by the quest remaining at 0/1

**Comment by wow-mania** [comment]
Fixed on next update.

**Comment by Calebrimbor** [comment]
Not fixed, still have the same issue. Also, I couldn't get the quest meself with all the required quests done. I had to .add in order ton test.
