### ISSUE TITLE
[Quest] Gizelton Caravan

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#261]
http://www.wow-mania.com/armory/?quest=5943

For this quest you'll need to escort a a group of Kodo's and 2 goblins. Talk with Cork Gizelton(http://www.wow-mania.com/armory/?npc=11625) to start the escort.

You can't interact with Cork Gizelton, so you can't start the escort.

**Comment by wow-mania** [comment]
You can. There are specific sections of the path where you can.

**Comment by wow-mania** [comment]
Fixed for Wednesday. This was a regression.

**Comment by Calebrimbor** [comment]
Fix is not working, issue still persists with the exact malfunction. Reopened the issue.

**Comment by Calebrimbor** [comment]
It got bugged worse.

![wowscrnshot_082616_112247](https://cloud.githubusercontent.com/assets/20358867/18000726/ae3b4d32-6b7f-11e6-95ff-656d95468c05.jpg)

**Comment by wow-mania** [comment]
It works fine for me please retest

**Comment by Calebrimbor** [comment]
Gizelton Caravan can now be accepted. On the route the caravan suddenly goes off-road. On coord 51.5, 73.0 it caused the quest to fail. One kodo went halfway underground. Also, when server started I had to kill Cork Gizelton and respawn him in order to start running. Addint the 'Tweaking' label.

![wowscrnshot_091616_163324](https://cloud.githubusercontent.com/assets/20358867/18589649/f30c3c98-7c2b-11e6-984b-5f8efc1796d1.jpg)
