### ISSUE TITLE
[Quest] The Drakkensryd

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#264]
http://www.wow-mania.com/armory/?quest=12886

This quest is doable! Players may find it hard but that it works almost as intended.

Once abandoned, Gretta the Arbiter(http://www.wow-mania.com/armory/?npc=29796) doesn't allow you to accept the quest anymore, it's greyed out. Also, when speaking to Thorim(http://www.wow-mania.com/armory/?npc=29445) you can complete the quest before actually doing it.

**Comment by Calebrimbor** [comment]
Labeled with 'Priority' since this quest is frequently reported.

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
You still can't retake quest once abandoned and you could still complete this quest @ Thorim without doing the quest at all

**Comment by Dragonfly414** [comment]
pitty that it still isnt fixed
