### ISSUE TITLE
[Quest] List of quests that summoned 2x mobs after the recent patch

### ISSUE THREAD

**Issue by Rockshark** [wow-mania/Redemption#305]
Here are a list of some of quest that need summoning and summoned 2x mobs, this was noticed after the recent patch.
Barren - Echeyakee - 2x normal mobs
              Ishamuhale - 2x normal mobs
              The binding - 2x normal mobs
Hinterland - Lard lost his lunch - 3x normal mobs now 6x
Hellfire - Natural Remedies - 2x elite mobs
Icecrown - If he cannot be turned - 2x elite generals
It seems that all summon quests will summon double and also quests which required to use x item on y will give a double count. You an easily deal with the normal mob but for elite it become undoable especially [If he cannot be turned] which is supposed to be solo quest.

**Comment by wow-mania** [comment]
Fixed.

**Comment by firstnebula** [comment]
Its not fixed still summons 2x elite generals on (if he cannot be turned) (19/08/2015)

**Comment by wow-mania** [comment]
Referring all related issue to a single place.
